package wrp

// DefaultAddress to connect to
var DefaultAddress = "wrp.host:4242"

// Mode is used to represent the mode of a client (read/write).
type Mode uint32

const (
	ModeRead  Mode = 1
	ModeWrite Mode = 1 << 1
)

// Key is a unique secret id generated by the client to identify itself to
// wrpd.
type Key string

// Size reprensents a window size.
type Size struct {
	Rows int
	Cols int
}

// Client represents a client connected to the wrp.
type Client struct {
	Username string
	Mode     Mode
}

// State is the struct sent over the network to update the client state.
type State struct {
	ID string

	WindowSize Size

	Host    Key
	Clients map[Key]Client
}

// HostUpdate represents an update to the wrp general state from its host.
type HostUpdate struct {
	ID  string
	Key string

	WindowSize Size
}

// ClientUpdate represents an update to the wrp state for a particular client,
// sent from the client or the host. A initial update is sent both when opening
// or connecting to a session.
type ClientUpdate struct {
	ID     string
	Key    string
	IsHost bool

	Username string
	Mode     Mode
}
