package wrp

// DefaultAddress to connect to
var DefaultAddress = "wrp.host:4242"

// Mode is used to represent the mode of a client (read/write/speak) as well as
// permission at the wrp level.
type Mode uint32

const (
	ModeRead  Mode = 1
	ModeWrite Mode = 1 << 1
	ModeSpeak Mode = 1 << 2
)

// Key is a unique secret ID generated by the client to identify itself to
// wrpd.
type Key string

// Size reprensents a window size.
type Size struct {
	Rows int
	Cols int
}

// Client represents a client connected to the wrp.
type Client struct {
	Username string
	Mode     Mode
}

// State is the struct sent over the network to update the client state.
type State struct {
	ID         string
	WindowSize Size

	Permissions Mode
	DefaultMode Mode

	Host    Key
	Clients map[Key]Client
}

// HostUpdate represents an update to the wrp general state from its host.
type HostUpdate struct {
	ID  string
	Key string

	WindowSize  Size
	DefaultMode Mode
	Permissions Mode
}

// ClientUpdate represents an update to the wrp state for a particular client,
// sent from the client or the host.
type ClientUpdate struct {
	ID  string
	Key string

	Username string
	Mode     Mode
}
